server:
  port: 8083

spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: root@1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # You can set this to "create", "update", "validate", etc.
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  config:
   import:
    - optional:configserver:http://localhost:8086

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka    
okta:
  oauth2:
    issuer: https://dev-58948983.okta.com/oauth2/default
    audience: api://default         